Strategic Server
----------------

Server that lets Players connect and play games.


HOW TO BUILD?
-------------
I've provided a simple ant build script.
So running with ant installed should be a simple:

+$ ant+

+$ java -jar StrategicServer.jar+

After Startup a TCP Interface on Port 4223 and on the console is opened. If no user database is found then a new one is created with the user "root" with password "root" is created.


LICENSE
-------

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 2
as published by the Free Software Foundation.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, see <http://www.gnu.org/licenses/>

